// Code generated by qtc from "generate_puzzle_user.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:1
package prompts

//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:1
func StreamGeneratePuzzleUser(qw422016 *qt422016.Writer, difficulty string, gamesPlayed uint, style string, styleAngles string, recentPuzzles []string, usedAnswers []string) {
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:1
	qw422016.N().S(`
Difficulty:`)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:2
	qw422016.E().S(difficulty)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:2
	qw422016.N().S(`
Games:`)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:3
	qw422016.N().D(int(gamesPlayed))
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:3
	qw422016.N().S(`
Style:`)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:4
	qw422016.E().S(style)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:4
	qw422016.N().S(` - try one of these angles: `)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:4
	qw422016.E().S(styleAngles)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:4
	qw422016.N().S(`
`)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:5
	if len(recentPuzzles) > 0 {
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:5
		qw422016.N().S(`
Recently used question -> answer pairs for this player - never repeat a question or anything too similar to these:
`)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:7
		for _, p := range recentPuzzles {
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:7
			qw422016.N().S(`
- `)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:8
			qw422016.E().S(p)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:8
			qw422016.N().S(`
`)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:9
		}
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:9
		qw422016.N().S(`
`)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:10
	}
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:10
	qw422016.N().S(`
`)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:11
	if len(usedAnswers) > 0 {
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:11
		qw422016.N().S(`
Answers this player has ever been given, across their entire history - NEVER reuse any of these, no matter how long ago or under what question:
`)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:13
		for _, a := range usedAnswers {
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:13
			qw422016.N().S(`
- `)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:14
			qw422016.E().S(a)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:14
			qw422016.N().S(`
`)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:15
		}
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:15
		qw422016.N().S(`
`)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:16
	}
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:16
	qw422016.N().S(`
`)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:17
}

//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:17
func WriteGeneratePuzzleUser(qq422016 qtio422016.Writer, difficulty string, gamesPlayed uint, style string, styleAngles string, recentPuzzles []string, usedAnswers []string) {
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:17
	StreamGeneratePuzzleUser(qw422016, difficulty, gamesPlayed, style, styleAngles, recentPuzzles, usedAnswers)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:17
}

//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:17
func GeneratePuzzleUser(difficulty string, gamesPlayed uint, style string, styleAngles string, recentPuzzles []string, usedAnswers []string) string {
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:17
	WriteGeneratePuzzleUser(qb422016, difficulty, gamesPlayed, style, styleAngles, recentPuzzles, usedAnswers)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:17
	qs422016 := string(qb422016.B)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:17
	return qs422016
//line pkg/chat/internal/prompts/generate_puzzle_user.qtpl:17
}
