// Code generated by qtc from "hint_user.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pkg/chat/internal/prompts/hint_user.qtpl:1
package prompts

//line pkg/chat/internal/prompts/hint_user.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pkg/chat/internal/prompts/hint_user.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pkg/chat/internal/prompts/hint_user.qtpl:1
func StreamHintUser(qw422016 *qt422016.Writer, hiddenPrompt, canonicalAnswer, history, guess, difficulty string, currentScore, previousBest int, historyLimit uint, gapHint string) {
//line pkg/chat/internal/prompts/hint_user.qtpl:1
	qw422016.N().S(`
Hidden:`)
//line pkg/chat/internal/prompts/hint_user.qtpl:2
	qw422016.E().S(hiddenPrompt)
//line pkg/chat/internal/prompts/hint_user.qtpl:2
	qw422016.N().S(`
Answer:`)
//line pkg/chat/internal/prompts/hint_user.qtpl:3
	qw422016.E().S(canonicalAnswer)
//line pkg/chat/internal/prompts/hint_user.qtpl:3
	qw422016.N().S(`
`)
//line pkg/chat/internal/prompts/hint_user.qtpl:4
	if historyLimit > 0 {
//line pkg/chat/internal/prompts/hint_user.qtpl:4
		qw422016.N().S(`
History(last `)
//line pkg/chat/internal/prompts/hint_user.qtpl:5
		qw422016.N().D(int(historyLimit))
//line pkg/chat/internal/prompts/hint_user.qtpl:5
		qw422016.N().S(` only):`)
//line pkg/chat/internal/prompts/hint_user.qtpl:5
		qw422016.E().S(history)
//line pkg/chat/internal/prompts/hint_user.qtpl:5
		qw422016.N().S(`
`)
//line pkg/chat/internal/prompts/hint_user.qtpl:6
	} else {
//line pkg/chat/internal/prompts/hint_user.qtpl:6
		qw422016.N().S(`
History:`)
//line pkg/chat/internal/prompts/hint_user.qtpl:7
		qw422016.E().S(history)
//line pkg/chat/internal/prompts/hint_user.qtpl:7
		qw422016.N().S(`
`)
//line pkg/chat/internal/prompts/hint_user.qtpl:8
	}
//line pkg/chat/internal/prompts/hint_user.qtpl:8
	qw422016.N().S(`
Guess:`)
//line pkg/chat/internal/prompts/hint_user.qtpl:9
	qw422016.E().S(guess)
//line pkg/chat/internal/prompts/hint_user.qtpl:9
	qw422016.N().S(`
GuessScore:`)
//line pkg/chat/internal/prompts/hint_user.qtpl:10
	qw422016.N().D(currentScore)
//line pkg/chat/internal/prompts/hint_user.qtpl:10
	qw422016.N().S(`/100
PreviousBestScore:`)
//line pkg/chat/internal/prompts/hint_user.qtpl:11
	qw422016.N().D(previousBest)
//line pkg/chat/internal/prompts/hint_user.qtpl:11
	qw422016.N().S(`/100
Difficulty:`)
//line pkg/chat/internal/prompts/hint_user.qtpl:12
	qw422016.E().S(difficulty)
//line pkg/chat/internal/prompts/hint_user.qtpl:12
	qw422016.N().S(`
GapHint:`)
//line pkg/chat/internal/prompts/hint_user.qtpl:13
	qw422016.E().S(gapHint)
//line pkg/chat/internal/prompts/hint_user.qtpl:13
	qw422016.N().S(`
`)
//line pkg/chat/internal/prompts/hint_user.qtpl:14
}

//line pkg/chat/internal/prompts/hint_user.qtpl:14
func WriteHintUser(qq422016 qtio422016.Writer, hiddenPrompt, canonicalAnswer, history, guess, difficulty string, currentScore, previousBest int, historyLimit uint, gapHint string) {
//line pkg/chat/internal/prompts/hint_user.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/chat/internal/prompts/hint_user.qtpl:14
	StreamHintUser(qw422016, hiddenPrompt, canonicalAnswer, history, guess, difficulty, currentScore, previousBest, historyLimit, gapHint)
//line pkg/chat/internal/prompts/hint_user.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line pkg/chat/internal/prompts/hint_user.qtpl:14
}

//line pkg/chat/internal/prompts/hint_user.qtpl:14
func HintUser(hiddenPrompt, canonicalAnswer, history, guess, difficulty string, currentScore, previousBest int, historyLimit uint, gapHint string) string {
//line pkg/chat/internal/prompts/hint_user.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/chat/internal/prompts/hint_user.qtpl:14
	WriteHintUser(qb422016, hiddenPrompt, canonicalAnswer, history, guess, difficulty, currentScore, previousBest, historyLimit, gapHint)
//line pkg/chat/internal/prompts/hint_user.qtpl:14
	qs422016 := string(qb422016.B)
//line pkg/chat/internal/prompts/hint_user.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/chat/internal/prompts/hint_user.qtpl:14
	return qs422016
//line pkg/chat/internal/prompts/hint_user.qtpl:14
}
