// Code generated by qtc from "score_intent_user.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pkg/chat/internal/prompts/score_intent_user.qtpl:1
package prompts

//line pkg/chat/internal/prompts/score_intent_user.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pkg/chat/internal/prompts/score_intent_user.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pkg/chat/internal/prompts/score_intent_user.qtpl:1
func StreamScoreIntentUser(qw422016 *qt422016.Writer, targetIntent, givenIntent string) {
//line pkg/chat/internal/prompts/score_intent_user.qtpl:1
	qw422016.N().S(`
Target:`)
//line pkg/chat/internal/prompts/score_intent_user.qtpl:2
	qw422016.E().S(targetIntent)
//line pkg/chat/internal/prompts/score_intent_user.qtpl:2
	qw422016.N().S(`
Given:`)
//line pkg/chat/internal/prompts/score_intent_user.qtpl:3
	qw422016.E().S(givenIntent)
//line pkg/chat/internal/prompts/score_intent_user.qtpl:3
	qw422016.N().S(`
JSON only, no backticks: {"intent_score": <0-100>, "gap": "<3-6 words>"}
`)
//line pkg/chat/internal/prompts/score_intent_user.qtpl:5
}

//line pkg/chat/internal/prompts/score_intent_user.qtpl:5
func WriteScoreIntentUser(qq422016 qtio422016.Writer, targetIntent, givenIntent string) {
//line pkg/chat/internal/prompts/score_intent_user.qtpl:5
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/chat/internal/prompts/score_intent_user.qtpl:5
	StreamScoreIntentUser(qw422016, targetIntent, givenIntent)
//line pkg/chat/internal/prompts/score_intent_user.qtpl:5
	qt422016.ReleaseWriter(qw422016)
//line pkg/chat/internal/prompts/score_intent_user.qtpl:5
}

//line pkg/chat/internal/prompts/score_intent_user.qtpl:5
func ScoreIntentUser(targetIntent, givenIntent string) string {
//line pkg/chat/internal/prompts/score_intent_user.qtpl:5
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/chat/internal/prompts/score_intent_user.qtpl:5
	WriteScoreIntentUser(qb422016, targetIntent, givenIntent)
//line pkg/chat/internal/prompts/score_intent_user.qtpl:5
	qs422016 := string(qb422016.B)
//line pkg/chat/internal/prompts/score_intent_user.qtpl:5
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/chat/internal/prompts/score_intent_user.qtpl:5
	return qs422016
//line pkg/chat/internal/prompts/score_intent_user.qtpl:5
}
