// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package puzzlesInternalPSQL

import (
	"time"

	gox "github.com/devlibx/gox-base/v2"
	pgVectorGo "github.com/pgvector/pgvector-go"
)

type Puzzle struct {
	PuzzleID              string              `json:"puzzle_id"`
	UserEmail             string              `json:"user_email"`
	HiddenPrompt          string              `json:"hidden_prompt"`
	CanonicalAnswer       string              `json:"canonical_answer"`
	HiddenPromptEmbedding pgVectorGo.Vector   `json:"hidden_prompt_embedding"`
	Messages              gox.StringObjectMap `json:"messages"`
	Metadata              gox.StringObjectMap `json:"metadata"`
	CreatedAt             time.Time           `json:"created_at"`
	UpdatedAt             time.Time           `json:"updated_at"`
}
