// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package puzzlesInternalPSQL

import (
	"context"
)

type Querier interface {
	CreatePuzzle(ctx context.Context, arg CreatePuzzleParams) (Puzzle, error)
	DeletePuzzlesByUser(ctx context.Context, userEmail string) error
	GetPuzzleByID(ctx context.Context, puzzleID string) (Puzzle, error)
	// Deliberately narrow: still excludes hidden_prompt_embedding and messages,
	// the genuinely expensive columns (a 768-dim vector plus a growing JSONB
	// blob, per row) - full puzzle data for those still goes through
	// GetPuzzleByID instead. hidden_prompt itself is a plain short text column
	// (comparable cost to canonical_answer, already selected below) and is
	// included so puzzle generation can build a per-user "don't repeat these
	// questions" list without a second query.
	GetPuzzlesByUser(ctx context.Context, userEmail string) ([]GetPuzzlesByUserRow, error)
	// Optimistic concurrency: the caller must pass the updated_at it last read
	// (current_updated_at). If another write has landed in the meantime, this
	// matches zero rows instead of blindly overwriting the newer data.
	UpdatePuzzleMessages(ctx context.Context, arg UpdatePuzzleMessagesParams) (Puzzle, error)
	// Optimistic concurrency: see UpdatePuzzleMessages above.
	UpdatePuzzleMetadata(ctx context.Context, arg UpdatePuzzleMetadataParams) (Puzzle, error)
}

var _ Querier = (*Queries)(nil)
