// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package puzzlesInternalPSQL

import (
	"context"
	"time"

	gox "github.com/devlibx/gox-base/v2"
	pgVectorGo "github.com/pgvector/pgvector-go"
)

const createPuzzle = `-- name: CreatePuzzle :one
INSERT INTO puzzles (
    puzzle_id,
    user_email,
    hidden_prompt,
    canonical_answer,
    hidden_prompt_embedding,
    messages,
    metadata
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING puzzle_id, user_email, hidden_prompt, canonical_answer, hidden_prompt_embedding, messages, metadata, created_at, updated_at
`

type CreatePuzzleParams struct {
	PuzzleID              string              `json:"puzzle_id"`
	UserEmail             string              `json:"user_email"`
	HiddenPrompt          string              `json:"hidden_prompt"`
	CanonicalAnswer       string              `json:"canonical_answer"`
	HiddenPromptEmbedding pgVectorGo.Vector   `json:"hidden_prompt_embedding"`
	Messages              gox.StringObjectMap `json:"messages"`
	Metadata              gox.StringObjectMap `json:"metadata"`
}

func (q *Queries) CreatePuzzle(ctx context.Context, arg CreatePuzzleParams) (Puzzle, error) {
	row := q.db.QueryRow(ctx, createPuzzle,
		arg.PuzzleID,
		arg.UserEmail,
		arg.HiddenPrompt,
		arg.CanonicalAnswer,
		arg.HiddenPromptEmbedding,
		arg.Messages,
		arg.Metadata,
	)
	var i Puzzle
	err := row.Scan(
		&i.PuzzleID,
		&i.UserEmail,
		&i.HiddenPrompt,
		&i.CanonicalAnswer,
		&i.HiddenPromptEmbedding,
		&i.Messages,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePuzzlesByUser = `-- name: DeletePuzzlesByUser :exec
DELETE FROM puzzles
WHERE user_email = $1
`

func (q *Queries) DeletePuzzlesByUser(ctx context.Context, userEmail string) error {
	_, err := q.db.Exec(ctx, deletePuzzlesByUser, userEmail)
	return err
}

const getPuzzleByID = `-- name: GetPuzzleByID :one
SELECT puzzle_id, user_email, hidden_prompt, canonical_answer, hidden_prompt_embedding, messages, metadata, created_at, updated_at
FROM puzzles
WHERE puzzle_id = $1
`

func (q *Queries) GetPuzzleByID(ctx context.Context, puzzleID string) (Puzzle, error) {
	row := q.db.QueryRow(ctx, getPuzzleByID, puzzleID)
	var i Puzzle
	err := row.Scan(
		&i.PuzzleID,
		&i.UserEmail,
		&i.HiddenPrompt,
		&i.CanonicalAnswer,
		&i.HiddenPromptEmbedding,
		&i.Messages,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPuzzlesByUser = `-- name: GetPuzzlesByUser :many
SELECT puzzle_id, canonical_answer, hidden_prompt, metadata, created_at, updated_at
FROM puzzles
WHERE user_email = $1
ORDER BY created_at DESC
`

type GetPuzzlesByUserRow struct {
	PuzzleID        string              `json:"puzzle_id"`
	CanonicalAnswer string              `json:"canonical_answer"`
	HiddenPrompt    string              `json:"hidden_prompt"`
	Metadata        gox.StringObjectMap `json:"metadata"`
	CreatedAt       time.Time           `json:"created_at"`
	UpdatedAt       time.Time           `json:"updated_at"`
}

// Deliberately narrow: still excludes hidden_prompt_embedding and messages,
// the genuinely expensive columns (a 768-dim vector plus a growing JSONB
// blob, per row) - full puzzle data for those still goes through
// GetPuzzleByID instead. hidden_prompt itself is a plain short text column
// (comparable cost to canonical_answer, already selected below) and is
// included so puzzle generation can build a per-user "don't repeat these
// questions" list without a second query.
func (q *Queries) GetPuzzlesByUser(ctx context.Context, userEmail string) ([]GetPuzzlesByUserRow, error) {
	rows, err := q.db.Query(ctx, getPuzzlesByUser, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPuzzlesByUserRow{}
	for rows.Next() {
		var i GetPuzzlesByUserRow
		if err := rows.Scan(
			&i.PuzzleID,
			&i.CanonicalAnswer,
			&i.HiddenPrompt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePuzzleMessages = `-- name: UpdatePuzzleMessages :one
UPDATE puzzles
SET
    messages = $2,
    updated_at = NOW()
WHERE puzzle_id = $1 AND updated_at = $3
RETURNING puzzle_id, user_email, hidden_prompt, canonical_answer, hidden_prompt_embedding, messages, metadata, created_at, updated_at
`

type UpdatePuzzleMessagesParams struct {
	PuzzleID  string              `json:"puzzle_id"`
	Messages  gox.StringObjectMap `json:"messages"`
	UpdatedAt time.Time           `json:"updated_at"`
}

// Optimistic concurrency: the caller must pass the updated_at it last read
// (current_updated_at). If another write has landed in the meantime, this
// matches zero rows instead of blindly overwriting the newer data.
func (q *Queries) UpdatePuzzleMessages(ctx context.Context, arg UpdatePuzzleMessagesParams) (Puzzle, error) {
	row := q.db.QueryRow(ctx, updatePuzzleMessages, arg.PuzzleID, arg.Messages, arg.UpdatedAt)
	var i Puzzle
	err := row.Scan(
		&i.PuzzleID,
		&i.UserEmail,
		&i.HiddenPrompt,
		&i.CanonicalAnswer,
		&i.HiddenPromptEmbedding,
		&i.Messages,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePuzzleMetadata = `-- name: UpdatePuzzleMetadata :one
UPDATE puzzles
SET
    metadata = $2,
    updated_at = NOW()
WHERE puzzle_id = $1 AND updated_at = $3
RETURNING puzzle_id, user_email, hidden_prompt, canonical_answer, hidden_prompt_embedding, messages, metadata, created_at, updated_at
`

type UpdatePuzzleMetadataParams struct {
	PuzzleID  string              `json:"puzzle_id"`
	Metadata  gox.StringObjectMap `json:"metadata"`
	UpdatedAt time.Time           `json:"updated_at"`
}

// Optimistic concurrency: see UpdatePuzzleMessages above.
func (q *Queries) UpdatePuzzleMetadata(ctx context.Context, arg UpdatePuzzleMetadataParams) (Puzzle, error) {
	row := q.db.QueryRow(ctx, updatePuzzleMetadata, arg.PuzzleID, arg.Metadata, arg.UpdatedAt)
	var i Puzzle
	err := row.Scan(
		&i.PuzzleID,
		&i.UserEmail,
		&i.HiddenPrompt,
		&i.CanonicalAnswer,
		&i.HiddenPromptEmbedding,
		&i.Messages,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
