// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package usersInternalMySQL

import (
	"time"

	utils "hidden-prompt-backend/pkg/utils"
)

type User struct {
	UserEmail    string        `json:"user_email"`
	PasswordHash string        `json:"password_hash"`
	IsVerified   bool          `json:"is_verified"`
	Metadata     utils.JSONMap `json:"metadata"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
}
