// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package usersInternalMySQL

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteUserByEmail(ctx context.Context, userEmail string) error
	GetUserByEmail(ctx context.Context, userEmail string) (User, error)
	UpdateUserVerificationToTrue(ctx context.Context, userEmail string) error
}

var _ Querier = (*Queries)(nil)
