// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package usersInternalMySQL

import (
	"context"

	utils "hidden-prompt-backend/pkg/utils"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    user_email,
    password_hash,
    is_verified,
    metadata
) VALUES (
    ?, ?, ?, ?
)
`

type CreateUserParams struct {
	UserEmail    string        `json:"user_email"`
	PasswordHash string        `json:"password_hash"`
	IsVerified   bool          `json:"is_verified"`
	Metadata     utils.JSONMap `json:"metadata"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.UserEmail,
		arg.PasswordHash,
		arg.IsVerified,
		arg.Metadata,
	)
	return err
}

const deleteUserByEmail = `-- name: DeleteUserByEmail :exec
DELETE FROM users
WHERE user_email = ?
`

func (q *Queries) DeleteUserByEmail(ctx context.Context, userEmail string) error {
	_, err := q.db.ExecContext(ctx, deleteUserByEmail, userEmail)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_email, password_hash, is_verified, metadata, created_at, updated_at
FROM users
WHERE user_email = ?
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, userEmail string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, userEmail)
	var i User
	err := row.Scan(
		&i.UserEmail,
		&i.PasswordHash,
		&i.IsVerified,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserVerificationToTrue = `-- name: UpdateUserVerificationToTrue :exec
UPDATE users
SET
    is_verified = TRUE
WHERE user_email = ?
`

func (q *Queries) UpdateUserVerificationToTrue(ctx context.Context, userEmail string) error {
	_, err := q.db.ExecContext(ctx, updateUserVerificationToTrue, userEmail)
	return err
}
